name: Samuel Noonan
favicon: null
layout_spectrum: 0.2473
typography_spectrum: 0.2508812453597784
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7298af'
    - '#06050b'
    - '#f59eae'
    - '#44f1f8'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
