name: Samuel Noonan
favicon: null
layout_spectrum: 0.2473
typography_spectrum: 0.2508812453597784
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8bfe8'
    - '#030b2f'
    - '#9e142e'
    - '#5d4611'
    - '#12718e'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
